services:
  - type: web
    name: hqhub-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist/frontend/browser
    routes:
      - type: rewrite
        source: /api/*
        destination: https://hqhub-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html