services:
  - type: web
    name: hqhub-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist/frontend/browser
    routes:
      - type: rewrite
        source: /guia-de-leitura/ordem-de-leitura-mutante
        destination: /guia-xmen-compartilhar.html
      - type: rewrite
        source: /hq/*
        destination: https://hqhub-backend.onrender.com/api/compartilhar/hq/*
      - type: rewrite
        source: /compartilhar/hq/postagem/*
        destination: https://hqhub-backend.onrender.com/api/compartilhar/postagens/*/v16
      - type: rewrite
        source: /api/*
        destination: https://hqhub-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
