-- Corrige as capas da primeira serie mensal de Superman da Panini (2002-2012).
-- Fonte: listagem por numero da colecao na Excelsior Comics. A edicao 22 nao
-- consta nessa listagem e permanece intocada ate haver fonte verificavel.
WITH capas(numero, url_capa) AS (
    VALUES
        (1, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-01.jpg'),
        (2, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-02.jpg'),
        (3, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-03.jpg'),
        (4, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-04.jpg'),
        (5, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-05.jpg'),
        (6, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-06.jpg'),
        (7, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-07.jpg'),
        (8, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-08.jpg'),
        (9, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-09.jpg'),
        (10, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-10.jpg'),
        (11, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-11.jpg'),
        (12, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-12.jpg'),
        (13, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-13.jpg'),
        (14, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-14.jpg'),
        (15, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-15.jpg'),
        (16, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-16.jpg'),
        (17, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-17.jpg'),
        (18, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-18.jpg'),
        (19, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-19.jpg'),
        (20, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-20.jpg'),
        (21, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-21.jpg'),
        (23, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-23.jpg'),
        (24, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-24.jpg'),
        (25, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-25.jpg'),
        (26, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-26.jpg'),
        (27, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-27.jpg'),
        (28, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-28.jpg'),
        (29, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-29.jpg'),
        (30, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-30.jpg'),
        (31, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-31.jpg'),
        (32, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-32.jpg'),
        (33, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-33.jpg'),
        (34, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-34.jpg'),
        (35, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-35.jpg'),
        (36, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-36.jpg'),
        (37, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-37.jpg'),
        (38, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-38.jpg'),
        (39, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-39.jpg'),
        (40, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-40.jpg'),
        (41, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-41.jpg'),
        (42, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-42.jpg'),
        (43, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2017/08/superman-panini-1serie-43.jpg'),
        (44, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-44.jpg'),
        (45, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-45.jpg'),
        (46, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-46.jpg'),
        (47, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-47.jpg'),
        (48, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-48.jpg'),
        (49, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-49.jpg'),
        (50, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-50.jpg'),
        (51, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-51.jpg'),
        (52, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-52.jpg'),
        (53, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-53.jpg'),
        (54, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-54.jpg'),
        (55, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-55.jpg'),
        (56, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2019/07/superman-panini-1aserie-56.png'),
        (57, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-57.jpg'),
        (58, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2019/07/superman-panini-1aserie-58.png'),
        (59, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-59.jpg'),
        (60, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-60.jpg'),
        (61, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-61.jpg'),
        (62, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-62.jpg'),
        (63, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-63.jpg'),
        (64, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-64.jpg'),
        (65, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-65.jpg'),
        (66, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-66.jpg'),
        (67, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-67.jpg'),
        (68, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-68.jpg'),
        (69, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-69.jpg'),
        (70, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-70.jpg'),
        (71, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-71.jpg'),
        (72, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-72.jpg'),
        (73, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-73.jpg'),
        (74, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-74.jpg'),
        (75, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-75.jpg'),
        (76, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-76.jpg'),
        (77, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-77.jpg'),
        (78, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-78.jpg'),
        (79, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-79.jpg'),
        (80, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-80.jpg'),
        (81, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-81.jpg'),
        (82, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-82.jpg'),
        (83, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-83.jpg'),
        (84, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-84.jpg'),
        (85, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-85.jpg'),
        (86, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-86.jpg'),
        (87, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-87.jpg'),
        (88, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-88.jpg'),
        (89, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-89.jpg'),
        (90, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-90.jpg'),
        (91, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-91.jpg'),
        (92, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-92.jpg'),
        (93, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2023/03/superman-panini-1o-serie-93.jpeg'),
        (94, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/10/superman-94.jpg'),
        (95, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-95.jpg'),
        (96, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-96.jpg'),
        (97, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-97.jpg'),
        (98, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-98.jpg'),
        (99, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-99.jpg'),
        (100, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-100.jpg'),
        (101, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-101.jpg'),
        (102, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-102.jpg'),
        (103, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-103.jpg'),
        (104, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-104.jpg'),
        (105, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-105.jpg'),
        (106, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-106.jpg'),
        (107, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-107.jpg'),
        (108, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2014/07/superman-108.jpg'),
        (109, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-109.jpg'),
        (110, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-110.jpg'),
        (111, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-111.jpg'),
        (112, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-112.jpg'),
        (113, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-113.jpg'),
        (114, 'https://excelsiorcomics.com.br/loja/wp-content/uploads/2013/06/superman-panini-114.jpg')
)
UPDATE edicoes edicao
SET url_capa = capa.url_capa,
    url_origem = 'https://excelsiorcomics.com.br/serie/superman-panini-1o-serie/',
    fonte_externa = 'EXCELSIOR',
    data_atualizacao = CURRENT_TIMESTAMP
FROM series serie
JOIN editoras editora ON editora.id = serie.editora_id
JOIN capas capa ON true
WHERE edicao.serie_id = serie.id
  AND hqhub_normalizar_titulo_serie(serie.titulo) =
      hqhub_normalizar_titulo_serie('Superman 1 Serie')
  AND hqhub_normalizar_titulo_serie(editora.nome) =
      hqhub_normalizar_titulo_serie('Panini')
  AND coalesce(serie.volume, 1) = 1
  AND CASE WHEN trim(edicao.numero) ~ '^0*[0-9]+$'
           THEN trim(edicao.numero)::integer END = capa.numero
  AND edicao.url_capa IS DISTINCT FROM capa.url_capa;
