quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hqhub

quarkus.hibernate-orm.database.generation=none

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

quarkus.http.port=8080

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

mp.jwt.verify.issuer=hqhub
smallrye.jwt.verify.algorithm=HS256
smallrye.jwt.verify.key=${HQHUB_JWT_SEGREDO:segredo-dev-hqhub-com-pelo-menos-32-caracteres}
