quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${HQHUB_DB_USUARIO:postgres}
quarkus.datasource.password=${HQHUB_DB_SENHA:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://${HQHUB_DB_HOST:localhost}:${HQHUB_DB_PORT:5433}/hqhub

quarkus.hibernate-orm.database.generation=none

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

quarkus.http.port=8080

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
quarkus.swagger-ui.persist-authorization=true

mp.jwt.verify.issuer=hqhub
smallrye.jwt.verify.algorithm=HS256
smallrye.jwt.verify.key.location=jwt-segredo.jwk
hqhub.jwt.segredo=${HQHUB_JWT_SEGREDO:segredo-dev-hqhub-com-pelo-menos-32-caracteres}

hqhub.integracoes.marvel.chave-publica=${HQHUB_MARVEL_CHAVE_PUBLICA:}
hqhub.integracoes.marvel.chave-privada=${HQHUB_MARVEL_CHAVE_PRIVADA:}
hqhub.integracoes.comicvine.chave-api=${HQHUB_COMICVINE_CHAVE_API:}
